
 const response = {
    list:[
        {
            "rank":"1",
            "points":"1025",
            "name":"John Doe",
            "age":"27"
        },
        {
            "rank":"3",
            "points":"245",
            "name":"Elizabeth",
            "age":"17"
        },
        {
            "rank":"2",
            "points":"566",
            "name":"Samantha",
            "age":"22"
        },
        {
            "rank":"10",
            "points":"878",
            "name":"Katherine",
            "age":"21"
        },
        {
            "rank":"11",
            "points":"778",
            "name":"Danerys",
            "age":"25"
        },
        {
            "rank":"12",
            "points":"983",
            "name":"Eva",
            "age":"23"
        },
        {
            "rank":"13",
            "points":"122",
            "name":"Ruby",
            "age":"22"
        },
        {
            "rank":"14",
            "points":"656",
            "name":"Valentina",
            "age":"27"
        },
        {
            "rank":"15",
            "points":"298",
            "name":"Mila",
            "age":"32"
        },
        {
            "rank":"4",
            "points":"497",
            "name":"Arya",
            "age":"31"
        },
        {
            "rank":"5",
            "points":"667",
            "name":"Jordan",
            "age":"40"
        },
        {
            "rank":"6",
            "points":"221",
            "name":"Christina",
            "age":"43"
        },
        {
            "rank":"9",
            "points":"333",
            "name":"Evangeline",
            "age":"26"
        },
        {
            "rank":"8",
            "points":"500",
            "name":"Jazmine",
            "age":"35"
        },
        {
            "rank":"7",
            "points":"765",
            "name":"Kira",
            "age":"33"
        }]}
        export default response
